---
# default domain
domain_name: isium.de

# default cluster name
cluster_name: dev

# default component state
component_state: present

cluster_public_domain: "{{ cluster_name }}.{{ domain_name }}"
kubeconfig: "{{ playbook_dir }}/../config/{{ cluster_name }}_kubeconfig"

config_dir: "{{ playbook_dir }}/../config"
cluster_backup_dir: "{{ config_dir }}/cache/{{ cluster_name }}"

google_credentials_path: "{{ config_dir }}/google-cloud.json"
