---
keycloak_realms:
  - realm_data:
      realm: "{{ keycloak_realm_name }}"
      enabled: true
      registrationAllowed: true
      registrationEmailAsUsername: true
      editUsernameAllowed: true
      resetPasswordAllowed: true
      rememberMe: true
      verifyEmail: true
      bruteForceProtected: true

      smtpServer:
        user: "{{ smtp.user }}"
        password: "{{ keycloak_smtp_password }}"
        replyToDisplayName: "{{ keycloak_realm_name }}"
        starttls: "{{ smtp.starttls }}"
        auth: "true"
        port: "{{ smtp.port }}"
        host: "{{ smtp.host }}"
        replyTo: "{{ smtp.replyTo }}"
        from: "{{ smtp.from }}"
        fromDisplayName: "{{ keycloak_realm_name }}"
        ssl: "{{ smtp.ssl }}"

    clients:
      - clientId: "coder"
        rootUrl: "https://coder.{{ cluster_public_domain }}"
        adminUrl: "https://coder.{{ cluster_public_domain }}"
        directAccessGrantsEnabled: true
        redirectUris:
          - "https://coder.{{ cluster_public_domain }}/*"
        secret: "{{ coder_client_secret }}"
