---
- name: app
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    namespace: "default"
    state: "{{ component_state }}"
    src: hello-app.yml

- name: public ingress
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    namespace: "default"
    state: "{{ component_state }}"
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: hello-public-ingress
        annotations:
          nginx.ingress.kubernetes.io/auth-url: "https://auth.dev.spaces.workshops.de/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.dev.spaces.workshops.de/oauth2/start?rd=$escaped_request_uri"
          # nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-email"
      spec:
        ingressClassName: nginx-public
        rules:
          - host: hello.{{ cluster_public_domain }}
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: hello-app
                      port:
                        number: 80
