---
- name: tmp dir
  file:
    path: "{{ role_path }}/tmp"
    state: directory

- name: coder template param file
  template:
    src: "params-devbox.yml.j2"
    dest: "{{ role_path }}/tmp/params-{{ item.name }}.yml"
    mode: 0600

- name: push template
  command: "{{ bin_dir }}/coder template push '{{ item.name }}' --ignore-lockfile --variables-file '{{ role_path }}/tmp/params-{{ item.name }}.yml' -d {{ role_path }}/coder_templates/devbox -y"
  ignore_errors: true
  register: result

- name: create template
  when: "result.rc != 0"
  command: "{{ bin_dir }}/coder template create '{{ item.name }}' --default-ttl {{ item.max_ttl }} --ignore-lockfile --variables-file '{{ role_path }}/tmp/params-{{ item.name }}.yml' -d {{ role_path }}/coder_templates/devbox -y"
  register: result
  until: result.rc == 0
  delay: 5
  retries: 5
