---
- name: setup admin user
  uri:
    url: "https://{{ coder_access_host }}/api/v2/users/first"
    method: POST
    body_format: json
    status_code: [ 200, 201, 409 ]
    body:
      email: "{{ coder_admin_email }}"
      organization: "{{ coder_organization }}"
      password: "{{ coder_admin_password }}"
      username: "{{ coder_admin_username }}"
  register: result

- name: api login
  uri:
    url: "https://{{ coder_access_host }}/api/v2/users/login"
    method: POST
    body_format: json
    status_code: [ 201 ]
    body:
      email: "{{ coder_admin_email }}"
      password: "{{ coder_admin_password }}"
  register: result

- name: set token fact
  set_fact:
    token: "{{ result.json.session_token }}"

- name: coder login
  command: "coder login https://{{ coder_access_host }} --token {{ token }}"
  changed_when: false

- name: devbox workspaces
  include_tasks: "devbox-workspace.yml"
  loop: "{{ coder_devbox_workspace_templates }}"