---
- name: namespace
  kubernetes.core.k8s:
    state: "present"
    kubeconfig: "{{ kubeconfig }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ namespace }}"

- name: include restore certs
  when:
    - "component_state == 'present'"
  include_tasks: restore_certs.yml

- name: google secret
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    namespace: "{{ namespace }}"
    state: "{{ component_state }}"
    definition: "{{ lookup('template', 'google_secret.yml.j2') | from_yaml }}"

- name: deploy issuer
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    namespace: "{{ namespace }}"
    state: "{{ component_state }}"
    definition: "{{ lookup('template', 'issuer.yml.j2') | from_yaml }}"

- name: certificate
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    namespace: "{{ namespace }}"
    state: "{{ component_state }}"
    definition: "{{ lookup('template', 'cert.yml.j2') | from_yaml }}"

- name: wait for cert ready
  when: "component_state == 'present'"
  command: kubectl --kubeconfig {{ kubeconfig }} wait --for=condition=ready certificate cluster-cert --timeout=180s -n {{ namespace }}

- name: include backup certs
  when:
    - "component_state == 'present'"
  include_tasks: backup_certs.yml

- name: Add chart repo
  kubernetes.core.helm_repository:
    name: k8s-nginx
    repo_url: "https://kubernetes.github.io/ingress-nginx"

# - name: process helm chart for internal ingress
#   vars:
#     http_node_port: 31080
#     https_node_port: 31443
#     default_ingress: true
#     ingress_class: nginx-internal
#   kubernetes.core.helm:
#     chart_ref: k8s-nginx/ingress-nginx
#     chart_version: "{{ nginx_controller_chart_version }}"
#     create_namespace: true
#     kubeconfig: "{{ kubeconfig }}"
#     release_name: nginx-ingress-internal
#     release_namespace: "{{ namespace }}"
#     release_values: "{{ lookup('template', role_path + '/templates/values.yml') | from_yaml }}"
#     update_repo_cache: true
#     wait: true
#     state: "{{ component_state }}"

- name: process helm chart for public ingress
  vars:
    http_node_port: 30080
    https_node_port: 30443
    default_ingress: false
    ingress_class: nginx-public
  kubernetes.core.helm:
    chart_ref: k8s-nginx/ingress-nginx
    chart_version: "{{ nginx_controller_chart_version }}"
    create_namespace: true
    kubeconfig: "{{ kubeconfig }}"
    release_name: nginx-ingress-public
    release_namespace: "{{ namespace }}"
    release_values: "{{ lookup('template', role_path + '/templates/values.yml') | from_yaml }}"
    update_repo_cache: true
    wait: true
    state: "{{ component_state }}"
