---
- name: deploy
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    google_credentials_path: "{{ playbook_dir }}/../config/google-cloud.json"
  roles:
    - cert_manager
    - nginx_ingress
    - postgres_base
    - hello_app
