---
- name: destroy
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
    - "{{ config_dir }}/app_config.yml"
  vars:
    component_state: absent
  roles:
    - role: kube_prometheus_stack
    - role: coder
    - role: postgres_instance
      vars:
        pg_namespace: coder
        pg_team_id: "main"
        pg_instance_name: "coder-db"
        pg_disk_size: "5Gi"
        pg_instances: 1
        pg_backup: true
        pg_clone: true
        pg_storage_provider: gs
        pg_bucket_backup_prefix: "{{ cluster_name }}/"
        pg_dbs:
          - user: "coder"
            db_name: "coder"
    - role: keycloak
    - role: postgres_instance
      vars:
        pg_namespace: keycloak
        pg_team_id: "main"
        pg_instance_name: "keycloak-db"
        pg_disk_size: "1Gi"
        pg_instances: 1
        pg_backup: true
        pg_clone: true
        pg_storage_provider: gs
        pg_bucket_backup_prefix: "{{ cluster_name }}/"
        pg_dbs:
          - user: "keycloak"
            db_name: "keycloak"
    - role: coder
    - role: nginx_ingress