---
- name: deploy
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    google_credentials_path: "{{ playbook_dir }}/../config/google-cloud.json"
  roles:
    - name: postgres_instance
      vars:
        namespace: pg-test
        pg_team_id: "main"
        pg_instance_name: "test-db"
        pg_disk_size: "1Gi"
        pg_instances: 1
        pg_backup: true
        pg_clone: true
        pg_storage_provider: gs
        pg_bucket_backup_prefix: "{{ cluster_name }}/"
        pg_dbs:
          - user: "mydb"
            db_name: "mydb"
