---
- name: terraform variables
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
    - "{{ default_config_dir }}/app_config.yml"
    - "{{ config_dir }}/app_config.yml"
  roles:
    - role: tf_vars
