---
- name: Create tfvars file
  template:
    src: "variables.tfvars.j2"
    dest: "{{ config_dir }}/variables.tfvars"

- name: Create env file
  template:
    src: "env.j2"
    dest: "{{ config_dir }}/env"
