---
- name: "wait for all pods are present"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    namespace: "{{ pg_namespace }}"
    api_version: "v1"
    kind: "Pod"
    label_selectors:
      - "cluster-name = {{ pg_team_id }}-{{ pg_instance_name }}"
      - "connection-pooler != {{ pg_team_id }}-{{ pg_instance_name }}-pooler"
  register: "pg_pod_query"
  retries: "{{ (pg_wait_timeout_seconds / 5) | int }}"
  delay: 5
  until: "(pg_pod_query.resources | length) == pg_instances"

- name: "wait for postgres pods to become ready"
  when: "component_state == 'present'"
  changed_when: false
  command: "kubectl --kubeconfig {{ kubeconfig }} -n {{ pg_namespace }}
    wait --for=condition=ready --timeout={{ pg_wait_timeout_seconds }}s -l cluster-name={{ pg_team_id }}-{{ pg_instance_name }} pod"
