---
- name: "namespace"
  kubernetes.core.k8s:
    state: "present"
    kubeconfig: "{{ kubeconfig }}"
    definition:
      apiVersion: "v1"
      kind: "Namespace"
      metadata:
        name: "{{ namespace }}"

- name: "s3 backup target secret"
  when: pg_backup
  kubernetes.core.k8s:
    state: "{{ component_state }}"
    kubeconfig: "{{ kubeconfig }}"
    namespace: "{{ namespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ pg_team_id }}-{{ pg_instance_name }}-s3-backup"
      type: Opaque
      data:
        s3_access_key: "{{ pg_s3_access_key | b64encode }}"
        s3_secret_key: "{{ pg_s3_secret_key | b64encode }}"

- name: "s3 clone source secret"
  when: pg_clone
  kubernetes.core.k8s:
    state: "{{ component_state }}"
    kubeconfig: "{{ kubeconfig }}"
    namespace: "{{ namespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ pg_team_id }}-{{ pg_instance_name }}-s3-clone"
      type: Opaque
      data:
        s3_access_key: "{{ pg_clone_s3_access_key | b64encode }}"
        s3_secret_key: "{{ pg_clone_s3_secret_key | b64encode }}"

- name: "query running postgres pods"
  when: "pg_backup"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    namespace: "{{ namespace }}"
    api_version: "v1"
    kind: "Pod"
    label_selectors:
      - "cluster-name = {{ pg_team_id }}-{{ pg_instance_name }}"
  register: "pg_pod_query"

- name: "update backup s3 access keys in running pods"
  when: pg_backup
  kubernetes.core.k8s_cp:
    kubeconfig: "{{ kubeconfig }}"
    namespace: "{{ namespace }}"
    remote_path: "/home/postgres/etc/wal-e.d/env/AWS_ACCESS_KEY_ID"
    content: "{{ pg_s3_access_key }}"
    pod: "{{ item.metadata.name }}"
  loop: "{{ pg_pod_query.resources }}"
  loop_control:
    label: "{{ item.metadata.name }}"

- name: "update backup s3 secret keys in running pods"
  when: pg_backup
  kubernetes.core.k8s_cp:
    kubeconfig: "{{ kubeconfig }}"
    namespace: "{{ namespace }}"
    remote_path: "/home/postgres/etc/wal-e.d/env/AWS_SECRET_ACCESS_KEY"
    content: "{{ pg_s3_secret_key }}"
    pod: "{{ item.metadata.name }}"
  loop: "{{ pg_pod_query.resources }}"
  loop_control:
    label: "{{ item.metadata.name }}"

- name: "check if clone source is present"
  when: pg_clone
  amazon.aws.aws_s3:
    s3_url: "{{ pg_clone_s3_endpoint }}"
    aws_access_key: "{{ pg_clone_s3_access_key }}"
    aws_secret_key: "{{ pg_clone_s3_secret_key }}"
    bucket: "{{ pg_clone_storage_bucket }}"
    region: "{{ pg_clone_s3_region }}"
    mode: "list"
    prefix: "{{ pg_clone_full_prefix }}"
  register: "s3_clone_target_list"
  until: "s3_clone_target_list is not failed"
  retries: 10
  delay: 5

- name: "set source exists fact"
  when: pg_clone
  ansible.builtin.set_fact:
    pg_clone_source_exists: "{{ s3_clone_target_list.s3_keys | length > 0 }}"

- name: "check if backup target is present"
  when: pg_backup
  amazon.aws.aws_s3:
    s3_url: "{{ pg_s3_endpoint }}"
    aws_access_key: "{{ pg_s3_access_key }}"
    aws_secret_key: "{{ pg_s3_secret_key }}"
    bucket: "{{ pg_storage_bucket }}"
    region: "{{ pg_s3_region }}"
    mode: "list"
    prefix: "{{ pg_backup_full_prefix }}"
  register: "s3_backup_target_list"

- name: "set backup exists fact"
  when: pg_backup
  ansible.builtin.set_fact:
    pg_backup_target_exists: "{{ s3_backup_target_list.s3_keys | length > 0 }}"
