---
- hosts: "localhost"
  gather_facts: false
  vars:
    provider: "ionos"
    env_id: "000"
    stage: "mgmt"
    kubeconfig: "~/.kube/config"

  roles:
    - name: "infrastructure_configuration"
    - name: "postgres_instance"
      vars:
        ionos_s3_dev_mode: true
        component_state: "present"
        pg_instance_name: "testdb2"
        pg_dbs:
          - user: "mydb"
            db_name: "mydb"
        pg_team_id: "myteam"
        pg_disk_size: "25Gi"
        pg_instances: 2
        pg_version: "12"
        # pg_clone: false
        # pg_backup: false
        # pg_clone_target_time: "2022-07-04T23:00:00+02:00"
