---
# Configuration for the Coder Development Cluster
# REQUIRED: You can create multible clusters in one project, this is the name of the cluster, must be unique per Google Cloud project
cluster_name: spring-boot

# OPTIONAL: Overriden defaults, see docs/default_app_config_template.yml
base_spot: true
workspace_machine_type: t2d-standard-4  # (4 vCPUs, 16 GB memory)

# Values for coder devbox workspace templates
coder_devbox_workspace_templates:
    # REQUIRED: Name of the workspace template
  - name: "SpringBoot"
    # REQUIRED: Docker image for the main devbox container
    devbox_image: isi006/java-training:latest
    # OPTIONAL: See docs/default_app_config_template.yml
    homedir_disk_size: 50Gi
    devbox_mem_limit: 10000
    docker_mem_limit: 2000
    desktop_setup: false
