---
- name: "add postres operator Repo"
  kubernetes.core.helm_repository:
    name: "postgres-operator-charts"
    repo_url: "https://opensource.zalando.com/postgres-operator/charts/postgres-operator"


- name: "deploy postgres operator"
  kubernetes.core.helm:
    chart_ref: "{{ pg_operator_chart_ref }}"
    chart_version: "{{ pg_operator_chart_version }}"
    create_namespace: true
    kubeconfig: "{{ kubeconfig }}"
    release_name: "postres-operator"
    release_namespace: "{{ pg_operator_namespace }}"
    state: "{{ component_state }}"
    values:
      configGeneral:
        resync_period: "{{ pg_operator_resync_period }}"
      configKubernetes:
        enable_pod_antiaffinity: "{{ pg_operator_anti_affinity }}"
      resources:
        limits:
          cpu: 1000m
          memory: 200Mi
        requests:
          cpu: 10m
          memory: 50Mi

- name: "cluster role"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: "{{ component_state }}"
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: zalando-postgres-viewer
      rules:
        - apiGroups:
            - acid.zalan.do
          resources:
            - "*"
          verbs:
            - get
            - list
            - watch