# from: https://dev.to/cloudx/multi-arch-docker-images-the-easy-way-with-github-actions-4k54

name: dev_run

# Controls when the workflow will run
on:
  workflow_dispatch:
    push:
      branches:
        - 'main'
      tags:
        - '*.*.*'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CLOUD: ${{ secrets.GOOGLE_CLOUD }}
      GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
      CLUSTER_NAME: dev
    environment:
      name: dev
      url: https://coder.dev.gke.isium.de
    steps:
      - name: credentials
        run: "mkdir -p config && echo ${GOOGLE_CLOUD} > config/google-cloud.json"
        shell: bash
      - name: run
        run: "docker run -v $(pwd)/config:/app/config isi006/coder-development-cluster:latest ${GCLOUD_PROJECT} ${CLUSTER_NAME}"
        shell: bash
