# from: https://dev.to/cloudx/multi-arch-docker-images-the-easy-way-with-github-actions-4k54

name: Run

# Controls when the workflow will run
on:
  workflow_dispatch:
    push:
      branches:
        - 'main'
      tags:
        - '*.*.*'

env:
  GOOGLE_CLOUD: ${{ secrets.GOOGLE_CLOUD }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: credentials
        run: "mkdir -p config && echo ${GOOGLE_CLOUD} > config/google-cloud.json"
        shell: bash
      - name: test
        run: "ls -l config"
        shell: bash
      # - name: runtest
      #   run: "docker run --entrypoint=gcloud isi006/coder-development-cluster:0.9.0 activate-service-account --key-file=config/google-cloud.json"
      #   shell: bash