# from: https://dev.to/cloudx/multi-arch-docker-images-the-easy-way-with-github-actions-4k54

name: Run

# Controls when the workflow will run
on:
  workflow_dispatch:
    push:
      branches:
        - 'main'
      tags:
        - '*.*.*'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: runtest
        run: "docker run --entrypoint=ls isi006/coder-development-cluster:0.9.0"
        shell: bash